name: Bug Report
description: 报告一个错误或问题
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您报告问题！请填写以下信息以帮助我们更好地理解和解决问题。

  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述
      description: 请详细描述遇到的问题
      placeholder: 描述您遇到的错误或问题...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 提供重现问题的详细步骤
      placeholder: |
        1. 执行 '...'
        2. 点击 '....'
        3. 看到错误 '....'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期望行为
      description: 描述您期望发生的行为
      placeholder: 应该发生什么...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 描述实际发生的行为
      placeholder: 实际发生了什么...
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 您使用的操作系统
      options:
        - Ubuntu/Debian
        - CentOS/RHEL/Fedora
        - macOS
        - Windows (WSL)
        - 其他 Linux 发行版
        - 其他
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun 版本
      description: 运行 `bun --version` 获取版本号
      placeholder: "例如: 1.0.0"
    validations:
      required: true

  - type: input
    id: cups-version
    attributes:
      label: CUPS 版本
      description: 运行 `cups-config --version` 获取版本号
      placeholder: "例如: 2.3.3"

  - type: textarea
    id: error-logs
    attributes:
      label: 错误日志
      description: 请提供相关的错误日志
      placeholder: 粘贴错误日志...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: 附加信息
      description: 添加任何其他可能有用的信息、截图或文件
      placeholder: 其他相关信息...

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      description: 在提交之前，请确认以下事项
      options:
        - label: 我已经搜索了现有的 Issues，确认这不是重复问题
          required: true
        - label: 我已经尝试在最新版本上重现此问题
          required: true
        - label: 我已经提供了足够的信息来重现问题
          required: true
